### PR TITLE
Change structure of generated package

### PR DESCRIPTION
**Pull request by akorobeinikov**

### CODE REVIEW

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Comment by evgeny-izutov** [comment]
@akorobeinikov Is it ready for review or should it be marked as draft?

**Comment by akorobeinikov** [comment]
> @akorobeinikov Is it ready for review or should it be marked as draft?

Convert to draft

**Comment by akorobeinikov** [comment]
move to ote

**Comment by akorobeinikov** [comment]
move to ote

**Pull request closed without merging**
